# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# New Test 3

name: Maven CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Set POM Build Version
      run: mvn versions:set -DnewVersion=1.0.0 --file ./my-app/pom.xml
      
    - name: Build with Maven
      run: mvn -B package --file ./my-app/pom.xml
    - name: tree view
      run: tree
    

    - name: Build and push Docker images
      uses: docker/setup-buildx-action@v2    
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: davideden/app:latest
